In [85]:
import pandas as pd
import numpy as np

In [86]:
data = pd.read_csv('Advertising.csv')#,index_col=0

In [87]:
y = data['sales']
x = data['TV']

In [88]:
def cost_func(weight,bias,y,x):
    cost=0
    nodes = len(y)
    for i in range(nodes):
        cost += (x[i]* weight + bias - y[i])**2
    return cost/nodes

In [89]:
weight = 0
bias= 0
cost = cost_func(weight,bias,y,x)

In [107]:
def update_weight(weight, bias, y, x , learning_rate):
    gradient_weight = 0
    gradient_bias = 0
    nodes = len(y)
    
    for i in range(nodes):
        gradient_weight += -2 * x[i] * (y[i] - (weight * x[i] + bias))
        gradient_bias += -2 * (y[i] - (weight * x[i] + bias))
        
    weight = weight - (gradient_weight/nodes) * learning_rate
    bias = bias - (gradient_bias/nodes) * learning_rate

    return weight, bias

In [113]:
def update_weights(radio, sales, weight, bias, learning_rate):
    weight_deriv = 0
    bias_deriv = 0
    companies = len(radio)

    for i in range(companies):
        # Calculate partial derivatives
        # -2x(y - (mx + b))
        weight_deriv += -2*radio[i] * (sales[i] - (weight*radio[i] + bias))

        # -2(y - (mx + b))
        bias_deriv += -2*(sales[i] - (weight*radio[i] + bias))

    # We subtract because the derivatives point in direction of steepest ascent
    weight -= (weight_deriv / companies) * learning_rate
    bias -= (bias_deriv / companies) * learning_rate

    return weight, bias

In [114]:
def training (epoch , weight, bias, y, x , learning_rate):
    for n in range(epoch) :
#         weight, bias = update_weight(weight, bias, y, x , learning_rate)
        weight, bias = update_weights(x,y,weight,bias,learning_rate)
        cost = cost_func(weight,bias,y,x)
        print(cost)

In [115]:
epoch =100
learning_rate = 0.01
training (epoch , weight, bias, y, x , learning_rate)

67072797.712930396
22417771491462.227
7.492704456171997e+18
2.504290851968841e+24
8.370105491200568e+29
2.797545096598774e+35
9.350250813124795e+40
3.1251396224008693e+46
1.0445171851209344e+52
3.491095700789184e+57
1.1668308923665636e+63
3.8999054969280163e+68
1.3034676219552254e+74
4.356587211725899e+79
1.4561046100173545e+85
4.8667466809962955e+90
1.62661549823032e+96
5.436646187924083e+101
1.817093333048053e+107
6.073281333520891e+112
2.0298762581568406e+118
6.784466908665468e+123
2.267576215536006e+129
7.57893282182141e+134
2.533111007433295e+140
8.466431259958866e+145
2.8297401128203924e+151
9.457856398096679e+156
3.1611046979809994e+162
1.0565378126917323e+168
3.5312723123672377e+173
1.1802591439980765e+179
3.944786818372687e+184
1.3184683314287692e+190
4.40672416791758e+195
1.4728619132675804e+201
4.922754710511772e+206
1.6453350936411407e+212
5.499212797636369e+217
1.838005006430839e+223
6.143174537848098e+228
2.0532367034053158e+234
6.862544657061766e+239
2.2936721855819246e+

/home/mary/.local/lib/python3.5/site-packages/ipykernel_launcher.py:5: RuntimeWarning: overflow encountered in double_scalars
  """


inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf
inf


In [ ]:
#multivariate linear regression 


In [168]:
Data = np.asarray(data)
features = Data[:,1:-1]
target = Data[:,-1]
target= target.reshape([-1,1])

In [169]:
weight = np.random.rand(3,1)

In [170]:
def prediction(features,target):
    prediction = np.dot(features,weight)
    return prediction

In [183]:
def cost_func(features,target,weight):
    cost = sum((np.dot(features,weight) - target )**2)/2*nodes
    return cost[0]


In [190]:
def update_weight(features,target,weight,lr):
    gradient = np.dot(np.transpose(target - np.dot(features,weight)),features) / nodes
    return weight-gradient*lr 

In [191]:
err=cost_func(features,target,weight)

In [192]:
(np.dot(features,weight) - target).shape

(200, 1)

In [193]:
np.dot(np.transpose(target - np.dot(features,weight)),features)

array([[-1827413.02947598,  -247552.23343868,  -377966.91234243]])

In [199]:
a = np.array([
   [1, 2],
   [3, 4]])

a.T
[[1, 3],
 [2, 4]]

[[1, 3], [2, 4]]

In [200]:
a.shape

(2, 2)

In [201]:
a

array([[1, 2],
       [3, 4]])

In [202]:
a.T

array([[1, 3],
       [2, 4]])